config/routes.rb
Rails.application.routes.draw do
  resources :people
  root 'static_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  validates :name, :lastname, presence: true
    
  def fullname
    "#{self.name} #{self.lastname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :set_people, only: [:index, :create, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    respond_to { |format| format.js }
  end

  # GET /people/1
  # GET /people/1.json
  def show
    respond_to { |format| format.js }
  end

  # GET /people/new
  def new
    @person = Person.new
    respond_to { |format| format.js }
  end

  # GET /people/1/edit
  def edit
    respond_to { |format| format.js }
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    @person.save
    respond_to { |format| format.js }
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end
    
    def set_people
      @people = Person.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :lastname)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <br></br>
    <main class="container" id="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/people/_errors.html.erb
<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>Por favor revise los siguientes problemas:</strong>
  <ul>
    <% @person.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/people/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @person.new_record? ? 'Agregar' : 'Editar' %> Persona</h3>
  </div>
  <%= form_for(@person, remote: true) do |f| %>
    <div class="panel-body">
      <div id="person_errors"></div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control reset' %>
      </div>
      
      <div class="form-group">
        <%= f.label :lastname %>
        <%= f.text_field :lastname, class: 'form-control reset' %>
      </div>
      
      <div class="form-group">
        <%= f.submit 'Guardar', data: { disable_with: 'Procesando...' }, class: 'btn btn-primary' %>
        <%= button_tag 'Cancelar', type: 'button', data: { disable_with: 'Procesando...'}, class: 'btn btn-default', id: 'cancelar-form' %>
      </div>
    </div>
  <% end %>
</div>

app/views/people/_index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to new_person_path, class: 'btn btn-primary pull-right', id: 'link_new_person', remote: true do %>
      <i class="glyphicon glyphicon-plus"></i>
    <% end %>
  </div>
</div>
<hr></hr>
<div class="row" id="row_index">
  <div class="col-md-12" id="col_index">
    <%= render 'index_content' %>
  </div>
  <div id="col_form"></div>
</div>

app/views/people/_index_content.html.erb
<div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Personas</h3>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% if @people.any? %>
            <% @people.each do |person| %>
              <tr>
                <td><%= person.fullname %></td>
                <td class="text-center">
                  <%= link_to person, class: 'btn btn-info btn-sm', remote: true do %>
                    <i class="glyphicon glyphicon-eye-open"></i>
                  <% end %>
                </td>
                <td class="text-center">
                  <%= link_to edit_person_path(person), class: 'btn btn-warning btn-sm', remote: true do %>
                    <i class="glyphicon glyphicon-pencil"></i>
                  <% end %>
                </td>
                <td class="text-center">
                  <%= link_to person, method: :delete, data: { confirm: 'Está Seguro?' }, class: 'btn btn-danger btn-sm', remote: true do %>
                    <i class="glyphicon glyphicon-minus"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="2">No hay personas registradas.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

app/views/people/_show.html.erb
<div class="jumbotron">
  <h1>Hola, <%= @person.fullname %></h1>
  <p>...</p>
  <p><%= link_to 'Atras', people_path, class: 'btn btn-default', remote: true %></p>
</div>

app/views/people/create.js.erb
<% if @person.errors.any? %>
  $("#person_errors").html("<%= j render 'errors' %>");
<% else %>
  $("#col_index").html("<%= j render 'index_content' %>");
  $(".reset").val('');
<% end %>

app/views/people/destroy.js.erb
<% if @person.errors.any? %>
  $("#person_errors").html("<%= j render 'errors' %>");
<% else %>
  $("#col_index").html("<%= j render 'index_content' %>");
<% end %>

app/views/people/edit.js.erb
$("#col_index").removeClass("col-md-12").addClass("col-md-6");
$("#col_form").addClass("col-md-6");
$("#col_form").html("<%= j render 'form', person: @person %>");
$("#link_new_person").addClass("disabled");
$("#link_edit_person").addClass("disabled");

app/views/people/index.js.erb
$("#main").html("<%= j render 'index' %>");

app/views/people/new.js.erb
$("#col_index").removeClass("col-md-12").addClass("col-md-6");
$("#col_form").addClass("col-md-6");
$("#col_form").html("<%= j render 'form', person: @person %>");
$("#link_new_person").addClass("disabled");

app/views/people/show.js.erb
$("#main").html("<%= j render 'show' %>");
setTimeout(function() { alert("el id de esta persona es <%= @person.id %>"); }, 400);

app/views/people/update.js.erb
<% if @person.errors.any? %>
  $("#person_errors").html("<%= j render 'errors' %>");
<% else %>
  $("#col_index").html("<%= j render 'index_content' %>");
<% end %>